"use strict";
let myName = document.getElementById("name");
let desig = document.getElementById("desig");
let phone = document.getElementById("phone");
let email = document.getElementById("email");
let add = document.getElementById("add");
let deg = document.getElementById("deg");
let uni = document.getElementById("uni");
let pass1 = document.getElementById("pass1");
let deg2 = document.getElementById("deg2");
let uni2 = document.getElementById("uni2");
let pass2 = document.getElementById("pass2");
let deg3 = document.getElementById("deg3");
let uni3 = document.getElementById("uni3");
let pass3 = document.getElementById("pass3");
let skill1 = document.getElementById("skill1");
let skill2 = document.getElementById("skill2");
let skill3 = document.getElementById("skill3");
let inp_lang = document.getElementById("inp_lang");
let inp_lang2 = document.getElementById("inp_lang2");
let company = document.getElementById("company");
let comLocation = document.getElementById("comLocation");
let jobTitle = document.getElementById("jobTitle");
let stYear = document.getElementById("stYear");
let endYear = document.getElementById("endYear");
let achv1 = document.getElementById("achv1");
let achv2 = document.getElementById("achv2");
let achv3 = document.getElementById("achv3");
let pic = document.getElementById("pic");
let submitBtn = document.getElementById("submitBtn");
let form = document.getElementById("form");
form?.addEventListener("submit", (e) => {
    e.preventDefault();
    localStorage.setItem("name", myName.value);
    localStorage.setItem("desig", desig.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("add", add.value);
    localStorage.setItem("deg", deg.value);
    localStorage.setItem("uni", uni.value);
    localStorage.setItem("pass1", pass1.value);
    localStorage.setItem("deg2", deg2.value);
    localStorage.setItem("uni2", uni2.value);
    localStorage.setItem("pass2", pass2.value);
    localStorage.setItem("deg3", deg3.value);
    localStorage.setItem("uni3", uni3.value);
    localStorage.setItem("pass3", pass3.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("inp_lang", inp_lang.value);
    localStorage.setItem("inp_lang2", inp_lang2.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("comLocation", comLocation.value);
    localStorage.setItem("jobTitle", jobTitle.value);
    localStorage.setItem("stYear", stYear.value);
    localStorage.setItem("endYear", endYear.value);
    localStorage.setItem("achv1", achv1.value);
    localStorage.setItem("achv2", achv2.value);
    localStorage.setItem("achv3", achv3.value);
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let textImg = reader.result;
            localStorage.setItem("profile_pic", textImg);
        });
        reader.readAsDataURL(pic.files[0]);
    }
    window.location.href = "./Resume/resume.html";
});
